= mrun
:toc:

== Overview

mrun (**_m_**ike's **_run_**time) is a low level, OCI compliant container runtime written in Go. It contains a package that you can download for interacting with the cgroup filesystem interface, documentation about container technology, a command line to use the tool and _more to come_...

[NOTE]
====
This runtime is created to be compatible with Linux operating systems that have systemd as the init system. I did not create this runtime to be reliable/platform independant. Do not rely on this runtime.
====

=== Original Goals of this project

Originally this project was created as a way to learn Linux and container technology. It ended up requiring a lot of research, hence the long pauses in development during the period of creating mrun.

== Reading and documentation

During the creation of this project I did a lot of reading on containerization. I have created documentation in `/docs`, which has some reading that can be a bit more approachable to a newcomer than trying to sieve through the internet for reading material.

The docs folder has reading about OCI standards, Kernel features that underpin container technology and additional miscellaneous docs. Enjoy!