= mrun-state
:toc:
:toclevels: 5

== Introduction and purpose

The purpose of these files are to create an API to interact with, and maintain the state of running containers on an mrun host. Essentially it is used to interact with the link:https://github.com/opencontainers/runtime-spec/blob/main/runtime.md#state[_state.json_] files for containers. In reality, this API interacts with the <<mrun runtime state directories>> and the data in this area of the root filesystem, to get information about containers running on the host.

== mrun runtime state directories

The `/var/run/mrun` directory contains data for each mrun managed container in the system.

=== Example directory structure

Say, for example, there are two running containers on the system, and their IDs are *_example-container_* and *_another-example-container_*.

[source, bash]
----
(base) ➜  ~ tree /var/run/mrun
/var/run/mrun
├── another-example-container-id
│   └── state.json
└── example-container-id
    └── state.json

2 directories, 2 files
----

If this is the state of the containers on the machine, the output of the `mrun ps` command would be as follows:

[source, bash]
----
(base) ➜  ~ mrun ps
CONTAINER ID          BUNDLE             CREATED   STATUS    PORTS     NAMES
example-container-id  /bundle-location   20min     running   8080      example-container
another-example-c...  /bundle-location   21min     stopped   8081      another-example-container
----

== Package Level Methods

These

=== Public

==== GetStateOfAllContainers

Returns a state object for all containers.

Internally this loops through each directory in /var/run/mrun, and reads the JSON contents into a ContainerState struct.

*Relevant Types:*

- <<ContainerState>>

[source, go]
----
func GetStateOfAllContainers() (*[]ContainerState, error)
----

==== GetContainerInfoByContainerID

Get the information of a container by the containerID

[source, go]
----
func GetContainerInfoByContainerID(containerID string) (Container, error)
----

==== InitContainerStateDirAndFile
Initialize a container's  state directory (_/var/run/mrun/<container-id>_) and create a link:https://github.com/opencontainers/runtime-spec/blob/main/schema/state-schema.json[container state file (state.json)] in that directory, in accordance with the link:https://github.com/opencontainers/runtime-spec/blob/main/schema/config-schema.json[config.json spec] for that container.

[source, go]
----
func InitContainerStateDirAndFile(containerID string, spec specs.Spec) error
----

==== GetContainerManager
Gets a ContainerManager object for a containerID.

*Relevant Types:*

- <<ContainerManager>>

[source, go]
----
func GetContainerManager(containerID string) ContainerManager
----

==== Utility Methods

===== NewContainerID

Returns a random alphanumeric 16 character string.

[source, go]
----
func NewContainerID() string
----

=== Private

==== getSubdirectories

Gets the subdirectories of a directory.

[source, go]
----
func getSubdirectories(root string) ([]string, error)
----

== ContainerManager

See <<GetContainerManager>>.

=== Public Receivers

==== UpdateContainerStateFile

Update a container _state.json_ file according to a specs.State object.

[source, go]
----
func (c *ContainerManager) UpdateContainerStateFile(state specs.State) error
----

==== DeleteStateFile

Remove the directory `/var/run/mrun/<container-id>` and in turn all it's children.

[source, go]
----
func (c *ContainerManager) DeleteStateFile() error
----

==== GetContainerState

Get state of a container from a container's state file.

[source, go]
----
func (c *ContainerManager) GetContainerState() (*specs.State, error)
----

==== CreateAndInitStateFile

Create an empty container state file (`_/var/run/mrun/container-id/state.json_`), and initialize this file with a JSON object representing the state of the container in link:https://github.com/opencontainers/runtime-spec/blob/main/schema/state-schema.json[standard OCI state.json format].

[source, go]
----
func (c *ContainerManager) CreateAndInitStateFile(state *specs.State) error
----

=== Private Receivers

==== getContainerStateFileName

Returns the absolute path of the container state file, i.e. _/var/run/mrun/<container-id>/state.json_.

[source, go]
----
func (c *ContainerManager) getContainerStateFileName() string
----

==== getContainerDirectoryName

Returns absolute path of the container directory, i.e. _/var/run/mrun/<container-id>_

[source, go]
----
func (c *ContainerManager) getContainerDirectoryName() string
----

== Types

==== ContainerManager
[source, go]
----
type ContainerManager struct {
	containerID string
}
----

==== ContainerState
[source, go]
----
type ContainerState struct {
	Name           string
	ID             string
	Command        string
	Status         string
	BundleLocation string
}
----