= containerd cgroupv2 package
:toc:

https://github.com/containerd/cgroups[Repo for the package.]

== Overview

== Package level methods

=== cgroupv2.Load

Takes an group name and <<InitOpts>> parameters, and returns a <<Manager>> object.

[source, go]
----
func Load(group string, opts ...InitOpts) (*Manager, error)
----

=== cgroupv2.LoadSystemd

Load an existing cgroup in a systemd system, and get a <<Manager>> object for that cgroup path.

[source, go]
----
func LoadSystemd(slice, group string) (*Manager, error)
----

==== Example usage

[source, go]
----
manager, err := cgroup2.LoadSystemd("/", "my-cgroup-abc.slice")
if err != nil {
	return err
}
----

=== cgroupv2.LoadAttachCgroupDeviceFilter
[source, go]
----
func LoadAttachCgroupDeviceFilter(insts asm.Instructions, license string, dirFD int)
----

=== cgroupv2.NestedGroupPath
[source, go]
----
func NestedGroupPath(suffix string) (string, error)
----

=== cgroupv2.NewCPUMax

Sets a new value in the `cpu.max` file and returns a <<CPUMax, CPUMax>> object.

[source, go]
----
func NewCPUMax(quota *int64, period *uint64) CPUMax
----

=== cgroupv2.NewManager

Creates a <<Manager>> object for an existing cgroup.

[source, go]
----
func NewManager(mountpoint string, group string, resources *Resources)
----

=== cgroupv2.NewSystemd

[source, go]
----
func NewSystemd(slice, group string, pid int, resources *Resources) (*Manager, error)
----

==== Example usage

The resulting slice will be located here on disk:

- /sys/fs/cgroup/my.slice/my-cgroup.slice/my-cgroup-abc.slice

[source, go]
----
import (
    "github.com/containerd/cgroups/v3/cgroup2"
    specs "github.com/opencontainers/runtime-spec/specs-go"
)

res := cgroup2.Resources{}
// dummy PID of -1 is used for creating a "general slice" to be used as a parent cgroup.
// see https://github.com/containerd/cgroups/blob/1df78138f1e1e6ee593db155c6b369466f577651/v2/manager.go#L732-L735
m, err := cgroup2.NewSystemd("/", "my-cgroup-abc.slice", -1, &res)
if err != nil {
	return err
}
----


=== cgroupv2.PidGroupPath

Get the path to teh cgroup for a pid.

[source, go]
----
func PidGroupPath(pid int) (string, error)
----

=== cgroupv2.ToResources

Get a <<Resources>> object for a link:https://github.com/opencontainers/runtime-spec/blob/main/specs-go/config.go#L455[specs.LinuxResources] object.

[source, go]
----
func ToResources(spec *specs.LinuxResources) *Resources
----

=== cgroupv2.VerifyGroupPath
[source, go]
----
func VerifyGroupPath(g string) error
----

=== cgroupv2.WithMountpoint

==== Relevant Types

- <<InitOpts>>

[source, go]
----
func WithMountpoint(path string) InitOpts
----

== Types

=== Event

Events are like notifications for when something occurs in a control group. There are files in the cgroup interface like

- `cgroup.events`
- `memory.events`
- `memory.events.local`
- `memory.swap.events`
- `pids.events`
- `pids.events.local`
- `hugetlb.<hugepagesize>.events.local`
- `misc.events`
- `misc.events.local`

[source, go]
----
type Event struct {
	Low     uint64
	High    uint64
	Max     uint64
	OOM     uint64
	OOMKill uint64
}
----

[[Resources]]
=== Resources

This object represents resources in a control group.

Relevant types:

- <<CPU, CPU>>
- <<Memory, Memory>>
- <<Pids, Pids>>
- <<IO, IO>>
- <<RDMA, RDMA>>
- <<HugeTlb, HugeTlb>>
- link:https://github.com/opencontainers/runtime-spec/blob/main/specs-go/config.go#L504[LinuxDeviceCgroup]

[source, go]
----
// Resources for a cgroups v2 unified hierarchy
type Resources struct {
	CPU     *CPU
	Memory  *Memory
	Pids    *Pids
	IO      *IO
	RDMA    *RDMA
	HugeTlb *HugeTlb
	// When len(Devices) is zero, devices are not controlled
	Devices []specs.LinuxDeviceCgroup
}
----

=== Value
[source, go]
----
// Value of a cgroup setting
type Value struct {
	filename string
	value    interface{}
}
----

=== BFQ

BFQ (Budget Fair Queueing) is an I/O scheduler used in Linux to manage allocation of disk bandwidth among different processes or groups of processes. Designed to ensure that all procs get fair share of I/O resources.

Can be used as part of I/O scheduler in for managing disk I/O bandwidth allocation between cgroups.

[source, go]
----
type BFQ struct {
	Weight uint16
}
----

=== CPU

This represents the CPU controller, which is a _threaded controller_.

The subcontrollers that this structure maps to are the

- `cpu.weight`
- `cpu.max`
- `cpuset.cpus`
- `cpuset.mems`

[source, go]
----
type CPU struct {
	Weight *uint64
	Max    CPUMax
	Cpus   string
	Mems   string
}
----

=== Entry

Dont know fully what this is. From looking at it it seems to be rate limiting operations on a device.

==== Relevant Types:
- <<IOType>>

==== Relevant Methods
-

[source, go]
----
type Entry struct {
	Type  IOType
	Major int64
	Minor int64
	Rate  uint64
}
----

=== HugeTlb
[source, go]
----
type HugeTlb []HugeTlbEntry
----

=== HugeTlbEntry

==== Relevant Types
- HugeTlb

[source, go]
----
type HugeTlbEntry struct {
	HugePageSize string
	Limit        uint64
}
----

=== IO

==== Relevant Types
- <<BFQ>>
- <<Entry>>

[source, go]
----
type IO struct {
	BFQ BFQ
	Max []Entry
}
----

=== Memory
[source, go]
----
type Memory struct {
	Swap *int64
	Min  *int64
	Max  *int64
	Low  *int64
	High *int64
}
----

=== Pids
[source, go]
----
type Pids struct {
	Max int64
}
----

=== RDMA
[source, go]
----
type RDMA struct {
	Limit []RDMAEntry
}
----

=== RDMAEntry
[source, go]
----
type RDMAEntry struct {
	Device     string
	HcaHandles uint32
	HcaObjects uint32
}
----

[[CgroupType]]
=== CgroupType

Represents the type of a control group. It is linked to the link:https://docs.kernel.org/admin-guide/cgroup-v2.html#core-interface-files[Core Interface File] `cgroup.type` file in the v2 heirarchy.

*Relevant Methods*:

- <<GetType, Manager.GetType>>
- <<SetType, Manager.SetType>>

[source, go]
----
// CgroupType represents the types a cgroup can be.
type CgroupType string

const (
	Domain         CgroupType = "domain"
	DomainThreaded CgroupType = "domain threaded"
	DomainInvalid  CgroupType = "domain invalid"
	Threaded       CgroupType = "threaded"
)
----

=== ControllerToggle
[source, go]
----
type ControllerToggle int

const (
	Enable ControllerToggle = iota + 1
	Disable
)
----

=== CPUMax

The maximum CPU bandwidth limit for a cgroup.

CPUMax represents the cpu.max file in a control group. This is a two value file which is only in non-root cgroups. The default is "max 100000".

Two value file `cpu.max` is in this format:

----
$MAX $PERIOD
----

Each value can be set to either "max" - indicating no limit, or an unsigned integer value.


[source, go]
----
type CPUMax string
----

=== IOType

Since the I/O controller is

This IOType is returned by functions...

Terminology:

- *BPS*: Bytes Per Second
- *IOPS*: I/O Operations Per Second

[source, go]
----
type IOType string

const (
	ReadBPS   IOType = "rbps"
	WriteBPS  IOType = "wbps"
	ReadIOPS  IOType = "riops"
	WriteIOPS IOType = "wiops"
)
----

=== InitOpts
[source, go]
----
type InitOpts func(c *InitConfig) error
----

=== State

==== deleted

State represents the current state of the cgroup.

A cgroup can appear in a "deleted state" when it is being deleted. A cgroup can not be immediately deleted in the kernel because some processes in the cgroup may still have open file descriptors. When it is in the deleted state it is essentially _being deleted_ per se in kernel space.

When you remove a cgroup with `rmdir` (on the cgroup directory) the kernel marks the cgroup for deletion. It remains there until all references to it are gone. If a cgroup is in a deleted state it is essentially pending cleanup.

==== frozen/thawed

Freezing a cgroup essentially suspends all processes in that cgroup. Thawing a cgroup resumes all the processes that were suspended. It is like pause/play on processes in a cgroup.

What a suspended process is is out of the scope of this documentation, but briefly, a suspended process stops running and does not consume CPU cycles.

No new processes are allowed spawn until cgroup is thawed.

When a cgroup is thawed all processes resume exactly where they left off.

[source, go]
----
// State is a type that represents the state of the current cgroup
type State string

const (
    Unknown State = ""
    Thawed  State = "thawed"
    Frozen  State = "frozen"
    Deleted State = "deleted"

    cgroupFreeze = "cgroup.freeze"
)
----

=== Manager

Manager is a

[source, go]
----
type Manager struct {
    unifiedMountpoint string
    path              string
}
----

=== ControllerToggle

Relevant methods:

- <<ToggleControllers, ToggleControllers>>

[source, go]
----
type ControllerToggle int

const (
    Enable ControllerToggle = iota + 1
    Disable
)
----


=== CgroupType

[source, go]
----
// CgroupType represents the types a cgroup can be.
type CgroupType string

const (
    Domain         CgroupType = "domain"
    DomainThreaded CgroupType = "domain threaded"
    DomainInvalid  CgroupType = "domain invalid"
    Threaded       CgroupType = "threaded"
)
----

=== InitConfig
[source, go]
----
type InitConfig struct {
	mountpoint string
}
----

=== IOType

[source, go]
----
type IOType string

const (
	ReadBPS   IOType = "rbps"
	WriteBPS  IOType = "wbps"
	ReadIOPS  IOType = "riops"
	WriteIOPS IOType = "wiops"
)
----

== manager.go

The manager struct seems to be the most comprehensive API in the cgroupv2 package. Here are some of the methods on it:

[[GetType]]
=== GetType

[source,go]
----
func (c *Manager) GetType() (CgroupType, error)
----

Gets the type of control group that the manager object represents. Returns a <<CgroupType, CgroupType>> and an error.

=== SetType

Set the type of a control group, using a <<CgroupType, CgroupType>>.

[source,go]
----
func (c *Manager) SetType(cgType CgroupType) error
----

==== Example usage

[source, go]
----
manager, err := cgroup2.LoadSystemd("/", "my-cgroup-abc.slice")
if err != nil {
	return err
}

cgType, err := manager.GetType()
if err != nil {
	return err
}

err = m.SetType(cgroup2.Threaded)
if err != nil {
	return err
}
----

=== RootControllers
[source,go]
----
func (c *Manager) RootControllers() ([]string, error)
----

=== Controllers
[source,go]
----
func (c *Manager) Controllers() ([]string, error)
----

=== Update

Takes a <<Resources,Resources>> object.

[source,go]
----
func (c *Manager) Update(resources *Resources) error
----

=== ToggleControllers

Enable/disable a controller by using the <<ControllerToggle, ControllerToggle>> type.

[source,go]
----
func (c *Manager) ToggleControllers(controllers []string, t ControllerToggle) error
----

=== NewChild


[source,go]
----
func (c *Manager) NewChild(name string, resources *Resources) (*Manager, error)
----

=== AddProc

Add a process to a cgroup by PID.

[source,go]
----
func (c *Manager) AddProc(pid uint64) error
----

=== AddThread

Add a thread to the cgroup by thread id (tid).

[source,go]
----
func (c *Manager) AddThread(tid uint64) error
----

=== Kill

Kill a cgroup.

[source,go]
----
func (c *Manager) Kill() error
----

=== Delete

Delete a cgroup.

[source,go]
----
func (c *Manager) Delete() error
----

=== Procs

Returns the pids that are in a cgroup.

[source,go]
----
func (c *Manager) Procs(recursive bool) ([]uint64, error)
----

=== Threads

Returns the tids for threads in the cgroup.

[source,go]
----
func (c *Manager) Threads(recursive bool) ([]uint64, error)
----

=== MoveTo

Move all items of a cgroup to another cgroup.

[source,go]
----
func (c *Manager) MoveTo(destination *Manager) error
----

=== Stat

Get a `stats.metrics` object for a cgroup.

[source,go]
----
func (c *Manager) Stat() (*stats.Metrics, error)
----

=== Freeze

[source,go]
----
func (c *Manager) Freeze() error
----

=== Thaw

[source,go]
----
func (c *Manager) Thaw() error
----

=== MemoryEventFD

[source,go]
----
func (c *Manager) MemoryEventFD() (int, uint32, error)
----

=== EventChan

[source,go]
----
func (c *Manager) EventChan() (<-chan Event, <-chan error)
----

=== DeleteSystemd

[source,go]
----
func (c *Manager) DeleteSystemd()
----
