= mrun standard conventions
:toc:

== Overiew

These conventions define global expectations of the mrun runtime.

The file locations are logically tied to the ID of a container, which is unique to each container.This should be solid provided there are solid procedures in place to prevent accidental user intervention.

== Purpose

The purpose of these conventions is to have a standard location, which allows for global management of containers.

=== Commands

This gives rise to commands like:

==== ps

[source, bash]
----
mrun ps
----

==== ls
[source, bash]
----
mrun ls
----

==== state
[source, bash]
----
mrun state <container-id>
----

==== create
[source, bash]
----
mrun create <container-id>
----

==== start
[source, bash]
----
mrun start <container-id>
----

==== kill
[source, bash]
----
mrun kill <container-id>
----

==== delete
[source, bash]
----
mrun delete <container-id>
----

== Runtime information

This is information that is live, stateful and is representative of the current state of a container/containers, managed by mrun.

=== Location of container state information, global

The file container.json

[source, bash]
----
/var/run/mrun
----

=== Location of container state information, per container

Located at `/var/run/mrun/<container-id>/state.json`.

=== Location of container state information, global

*There is no global state file.* This is retrieved programatically by mrun.

== Control group location

