// Code generated by MockGen. DO NOT EDIT.
// Source: container/apparmor.go
//
// Generated by this command:
//
//	mockgen -source=container/apparmor.go -destination=mocks/mock_apparmor.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
